GET http://127.0.0.1:3333/courses

###

@courseId = 27d0a4f0-5aa4-40d1-a913-edc36c2ed9a5
GET http://127.0.0.1:3333/courses/{{courseId}}

###

POST http://127.0.0.1:3333/courses
Content-Type: application/json

{
    "title": "Preact Course"
}