GET http://127.0.0.1:3333/courses

###

@courseId = 413c7bde-3988-4a15-96f6-e76be205658c
GET http://127.0.0.1:3333/courses/{{courseId}}

###

POST http://127.0.0.1:3333/courses
Content-Type: application/json

{
    "title": "Node.js Course"
}