GET http://127.0.0.1:3333/courses

###

@courseId = 92c07d8a-08bc-4b98-8a9f-c14341482563
GET http://127.0.0.1:3333/courses/{{courseId}}

###

POST http://127.0.0.1:3333/courses
Content-Type: application/json

{
    "title": "React.js Course"
}

###

POST http://127.0.0.1:3333/sessions
Content-Type: application/json

{
    "email": "Cesar.Xavier@live.com",
    "password": "123456"
}